### ISSUE TITLE
Local API instance connect to public GH pages repo

### ISSUE THREAD

**Issue by mstalfoort** [speedtracker/speedtracker-api#3]
For the past 2 days I've been testing your speedtracker implementation and I really like it.
Since I wanted to have it up and running quite fast I followed your documentation and indeed it's easy to install and setup, so a big thumbsup for that.

At the moment I've downloaded your API version of speedtracker and I want to connect this to my configured GH pages version, yet I'm not really successful.
The mongodb connection for instance is what's blocking me now to continue, can you help me out on this one on how to configure my local API instance?

**Comment by eduardoboucas** [comment]
The app will look for a `MONGODB_URI` environment variable (or a `database.uri` property in a local config file) containing a connection URI (like mongodb://something@some_host:port/database).

This first release of the platform was focused on people using the public API instance, which is why the documentation for the API layer were massively neglected. I would look at the [config schema](https://github.com/speedtracker/speedtracker-api/blob/master/config.js) to see what configuration parameters are expected and go from there.

It'd be great if you could document the process as you go through it! Let me know if you have any other issues.

**Comment by mstalfoort** [comment]
Understandable explanation, as said connecting with the public api went very easy

Is my assumption correct that I can connect from my local api to the mongo instance on my public github pages speedtracker?
If so, what would the uri be?
